const sampleAnswers = [
  {
    _table: {
      _base: {
        _airtable: {
          requesttimeout: 300000,
        },
        _id: 'appvxxitewzwrbrou',
      },
      id: 'null',
      name: 'spring quiz answers',
    },
    id: 'recanp6eyqyix2k8d',
    _rawjson: {
      id: 'recanp6eyqyix2k8d',
      fields: {
        geography_5: '5',
        geography_2: '2',
        geography_3: '3',
        geography_1: '1',
        geography_4: '4',
        teamname: 'the shiny shrimps',
      },
      createdtime: '2020-03-30t19:43:46.000z',
    },
    fields: {
      geography_5: '5',
      geography_2: '2',
      geography_3: '3',
      geography_1: '1',
      geography_4: '4',
      teamname: 'the shiny shrimps',
    },
  },
  {
    _table: {
      _base: {
        _airtable: {
          requesttimeout: 300000,
        },
        _id: 'appvxxitewzwrbrou',
      },
      id: 'null',
      name: 'spring quiz answers',
    },
    id: 'recewj8lumvfoturw',
    _rawjson: {
      id: 'recewj8lumvfoturw',
      fields: {
        books_6: 'ihg',
        news_3: 'hghj',
        books_5: 'hgh',
        geography_5: 'ghj',
        film_2: 'j',
        geography_2: 'gvbhjnkm',
        film_6: 'ghj',
        books_3: 'hjk',
        film_4: 'kjhg',
        geography_7: 'ghjk',
        pictures_9: 'hjk',
        geography_10: 'ghjk',
        geography_8: 'hj',
        film_9: 'hjjhg',
        books_2: 'hg',
        music_1: 'ghj',
        news_1: 'jhg',
        geography_3: 'bnjk',
        pictures_6: 'kjhg',
        pictures_1: 'jhg',
        books_1: 'hghj',
        news_8: 'jhghj',
        music_5: 'hg',
        music_2: 'ghj',
        news_5: 'hji',
        geography_6: 'bhj',
        music_8: 'hjjhghjjhg',
        film_1: 'ghjkh',
        music_7: 'jhg',
        pictures_10: 'kjhghjk',
        film_3: 'vghj',
        music_6: 'hgh',
        books_7: 'hj',
        pictures_2: 'hjkj',
        books_4: 'hghjk',
        music_4: 'gh',
        pictures_7: 'hjk',
        film_10: 'hj',
        books_10: 'hjk',
        news_6: 'ihg',
        books_9: 'kjhg',
        geography_1: 'fgvhbj',
        film_8: 'jhg',
        news_10: 'vghjk',
        music_3: 'gh',
        geography_4: 'ghjk',
        news_4: 'kkhg',
        pictures_5: 'vhj',
        teamname: 'anna test',
        books_8: 'kijhghj',
        film_7: 'hghj',
        news_9: 'kjh',
        news_2: 'hjkj',
        music_9: 'hjhgh',
        news_7: 'hjk',
        pictures_4: 'kjh',
        music_10: 'hj',
        pictures_3: 'hghj',
        pictures_8: 'jhg',
        geography_9: 'hj',
        film_5: 'hjkjh',
      },
      createdtime: '2020-03-31t17:22:54.000z',
    },
    fields: {
      books_6: 'ihg',
      news_3: 'hghj',
      books_5: 'hgh',
      geography_5: 'ghj',
      film_2: 'j',
      geography_2: 'gvbhjnkm',
      film_6: 'ghj',
      books_3: 'hjk',
      film_4: 'kjhg',
      geography_7: 'ghjk',
      pictures_9: 'hjk',
      geography_10: 'ghjk',
      geography_8: 'hj',
      film_9: 'hjjhg',
      books_2: 'hg',
      music_1: 'ghj',
      news_1: 'jhg',
      geography_3: 'bnjk',
      pictures_6: 'kjhg',
      pictures_1: 'jhg',
      books_1: 'hghj',
      news_8: 'jhghj',
      music_5: 'hg',
      music_2: 'ghj',
      news_5: 'hji',
      geography_6: 'bhj',
      music_8: 'hjjhghjjhg',
      film_1: 'ghjkh',
      music_7: 'jhg',
      pictures_10: 'kjhghjk',
      film_3: 'vghj',
      music_6: 'hgh',
      books_7: 'hj',
      pictures_2: 'hjkj',
      books_4: 'hghjk',
      music_4: 'gh',
      pictures_7: 'hjk',
      film_10: 'hj',
      books_10: 'hjk',
      news_6: 'ihg',
      books_9: 'kjhg',
      geography_1: 'fgvhbj',
      film_8: 'jhg',
      news_10: 'vghjk',
      music_3: 'gh',
      geography_4: 'ghjk',
      news_4: 'kkhg',
      pictures_5: 'vhj',
      teamname: 'anna test',
      books_8: 'kijhghj',
      film_7: 'hghj',
      news_9: 'kjh',
      news_2: 'hjkj',
      music_9: 'hjhgh',
      news_7: 'hjk',
      pictures_4: 'kjh',
      music_10: 'hj',
      pictures_3: 'hghj',
      pictures_8: 'jhg',
      geography_9: 'hj',
      film_5: 'hjkjh',
    },
  },
];

export default sampleAnswers;
