export default [
  {
    _table: {
      _base: {
        _airtable: { requestTimeout: 300000 },
        _id: 'appvXxiTEwZwrbroU',
      },
      id: null,
      name: 'Spring quiz answers',
    },
    id: 'recdGUspZTYilfdUA',
    _rawJson: {
      id: 'recdGUspZTYilfdUA',
      fields: {
        teamname: 'Freddie',
        a_1: 'Senegal',
        a_2: 'Ontario',
        a_5: 'Red, White, Green',
        a_3: 'East Germany',
        a_4: 'Benny',
        a_6: 'Lima',
        a_7: 'India',
        a_9: 'Norwegian',
        a_8: 'France',
        a_10: 'Flemish',
        b_1: 'False Alarm, I Feel It Coming, Starboy',
        b_2: '24',
        b_3: 'Men',
        b_4: 'Beyoncé',
        b_5: 'Ozymandas',
        b_6: 'Dan Sofer',
        b_7: 'True',
        b_8: 'Poisoning',
        b_9: 'They inspired TV shows',
        b_10: 'Ed Sheeran single - You',
        c_1: 'The Breakfast Club',
        c_2: 'Rapunzel 1985-1990',
        c_3: 'Sex and the City',
        c_4: 'The film where someone orgasms',
        c_5: 'Please',
        c_6: 'Stuart Little',
        c_7: 'Men In Black (1997-2002)',
        c_8: 'Her & also Marriage Story',
        c_9: 'Ed, Edd and Eddy',
        c_10: '3',
        d_1: 'Great Expectations',
        d_2: 'Hitchhikers Guide to the Galaxy',
        d_3: 'Avada Kedavra',
        d_4: 'Tom Hanks',
        d_5: 'A Clash of Castles',
        d_6:
          "I'm not going to make up a name here, it's not going to go down well.",
        d_7: '37',
        d_8: 'The Body',
        d_9: 'Stan Lee',
        d_10: 'I only came here to shitpost tbh',
        e_1: 'Born This Way',
        e_2: "Harry Potter and the Philosopher's Stone (Hermione Granger)",
        e_3: 'I need',
        e_4: 'to',
        e_5: 'go',
        e_6: 'but',
        e_7: 'it',
        e_8: 'was',
        e_9: 'the',
        e_10: 'best',
        f_1: 'quiz',
        f_2: 'ever',
        f_3: 'thank',
        f_4: 'you',
        f_5: 'bless',
        f_6: 'your',
        f_7: 'souls',
        f_8: 'and',
        f_9: 'your',
        f_10: 'soles, too.',
        score: 18,
      },
      createdTime: '2020-04-04T19:07:30.000Z',
    },
    fields: {
      teamname: 'Freddie',
      a_1: 'Senegal',
      a_2: 'Ontario',
      a_5: 'Red, White, Green',
      a_3: 'East Germany',
      a_4: 'Benny',
      a_6: 'Lima',
      a_7: 'India',
      a_9: 'Norwegian',
      a_8: 'France',
      a_10: 'Flemish',
      b_1: 'False Alarm, I Feel It Coming, Starboy',
      b_2: '24',
      b_3: 'Men',
      b_4: 'Beyoncé',
      b_5: 'Ozymandas',
      b_6: 'Dan Sofer',
      b_7: 'True',
      b_8: 'Poisoning',
      b_9: 'They inspired TV shows',
      b_10: 'Ed Sheeran single - You',
      c_1: 'The Breakfast Club',
      c_2: 'Rapunzel 1985-1990',
      c_3: 'Sex and the City',
      c_4: 'The film where someone orgasms',
      c_5: 'Please',
      c_6: 'Stuart Little',
      c_7: 'Men In Black (1997-2002)',
      c_8: 'Her & also Marriage Story',
      c_9: 'Ed, Edd and Eddy',
      c_10: '3',
      d_1: 'Great Expectations',
      d_2: 'Hitchhikers Guide to the Galaxy',
      d_3: 'Avada Kedavra',
      d_4: 'Tom Hanks',
      d_5: 'A Clash of Castles',
      d_6:
        "I'm not going to make up a name here, it's not going to go down well.",
      d_7: '37',
      d_8: 'The Body',
      d_9: 'Stan Lee',
      d_10: 'I only came here to shitpost tbh',
      e_1: 'Born This Way',
      e_2: "Harry Potter and the Philosopher's Stone (Hermione Granger)",
      e_3: 'I need',
      e_4: 'to',
      e_5: 'go',
      e_6: 'but',
      e_7: 'it',
      e_8: 'was',
      e_9: 'the',
      e_10: 'best',
      f_1: 'quiz',
      f_2: 'ever',
      f_3: 'thank',
      f_4: 'you',
      f_5: 'bless',
      f_6: 'your',
      f_7: 'souls',
      f_8: 'and',
      f_9: 'your',
      f_10: 'soles, too.',
      score: 18,
    },
  },
  {
    _table: {
      _base: {
        _airtable: { requestTimeout: 300000 },
        _id: 'appvXxiTEwZwrbroU',
      },
      id: null,
      name: 'Spring quiz answers',
    },
    id: 'recobl7QPFEw9v2n5',
    _rawJson: {
      id: 'recobl7QPFEw9v2n5',
      fields: {
        teamname: 'Testy',
        a_1: 'hi',
        a_2: 'hey',
        a_4: 'actually',
        b_3: 'I want to test evertyhing',
        b_4: 'Every case',
        d_1: 'missed out a whole category there',
      },
      createdTime: '2020-06-01T23:07:03.000Z',
    },
    fields: {
      teamname: 'Testy',
      a_1: 'hi',
      a_2: 'hey',
      a_4: 'actually',
      b_3: 'I want to test evertyhing',
      b_4: 'Every case',
      d_1: 'missed out a whole category there',
    },
  },
];
